{
 "title": "UI Performance Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CDP Performance Metrics Trend Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select timestamp as time, name as metric, value as duration from performance_metrics where name IN ('ScriptDuration', 'JSHeapTotalSize', 'JSHeapUsedSize', 'DomContentLoaded')"
    }
   ]
  },
  {
   "title": "Lighthouse Metrics Trend Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select timestamp as time, name as metric, value as duration from performance_metrics where name NOT IN ( 'performance', 'accessibility', 'ScriptDuration', 'JSHeapTotalSize', 'JSHeapUsedSize', 'DomContentLoaded')"
    }
   ]
  },
  {
   "title": "Score Trend Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select timestamp as time, name as metric, value as score from selenium.performance_metrics WHERE name IN ( 'accessibility', 'performance' )"
    }
   ]
  }
 ]
}